### ISSUE TITLE
Making fun of sexual assault is not okay at all

### ISSUE THREAD

**Issue by YRUSpawnCamping** [redeclipse/maps#163]
Do you think that making fun of sexual assault is okay? Because I just downloaded the game for the first time, started a practice match and was immediately greeted with this:

Auster by Alex "molexted" Foster

I noticed that (what I assume to be) the same person is listed in the base repository as "Alex "molex" Foster". So at least someone here agrees that this is a problem. Though I have to say, knowing the original name it still seems in bad taste to use a shortened version of it.

Keeping this in the game signals that you think "molexted" is an okay name. It is not.

**Comment by SniperGoth** [comment]
If my memory serves correctly, molex is the name of a power supply connector, and the entire name was just a play of words.

He hasn't been part of RE in years, as he has his own project to take care about nowadays, so all that remains are his map contributions from back in the day. 

But perhaps something could be done about it?

**Comment by qreeves** [comment]
The discrepancy is because I've been changing it from "molexted" to "molex" as each of his old contributions are updated. I share a rather similar sentiment about the name myself. 

If you see the name elsewhere, it is either an oversight, or in the case of this map, the content is planned to be removed unless significant work is done to fix it, at which point I'll put in the effort to actually have it fixed. 

Please note though that topics of this nature violate our rules. I'm a reasonable person, but an open source community is not the appropriate place for debates of a philosophical, political, or moral nature. There are better things to do and this behaviour always ultimately leads to a toxic and out of control community. 

Thank you for understanding. I will monitor the situation as it evolves and take appropriate action.

**Comment by garsipal** [comment]
Not sure how much of an effort it'd be to just update a few letters of a username that the user himself changed like 4 years ago. If anything you make sure the credits are up to date and the community feels heard if that offends anyone as a plus.

**Comment by 2404133455** [comment]
agreed, this is a very trivial fix since you can just boot up the map editor and change it without any issue

I understand wanting to make significant changes to maps instead of adding tiny updates like this, but honestly just doing this and getting it over with feels reasonably easy to accomplish

at least there's no need to do this for maps that are not official or updated to official map quality yet, I suppose, but then again I'm wondering what'd happen if a user in the future decided to make a map titled something offensive or put something like that in the author name, should there be any control over this or no?

**Comment by qreeves** [comment]
The updates change binary files which cannot store diffs in a git repository. Changing them frequently explodes the repository size.

If I take action now, it would just result in me removing the content entirely, as I have no desire to make significant changes to bring them up to the standard for re-inclusion in the map rotation.

**Comment by qreeves** [comment]
I'll reiterate separately: **this is not the place for this discussion.**

**Comment by YRUSpawnCamping** [comment]
Happy to see that this is moving forward.

Very, very disappointed to see that some people apparently **still** think rape culture is funny.

**Comment by MirceaKitsune** [comment]
Please see the previous comment. It states "**this is not the place for this discussion**". The issue has been closed as such, it's not even an actual technical issue to begin with.

I agree some evil things exist in this world, but please do NOT bring the morality wars here: Some of us don't want another project we care for ruined by culture wars and people making everything about personal feelings and social stuff. This is not Xonotic, nor the Doom communities where I've had friends abused over social justice issues unrelated to the projects themselves or anything said in their communities: I know this isn't about seeking revenge on people per say, but I've had a front row seat to seeing where these kinds of slippery slopes lead to.

I understand the whole thing is about an author picking a silly nickname. I don't believe it's intended to make fun of assault at all, it's just a funny name someone happened to pick and use. As such I don't mind at all since I don't think it's with bad intent, please don't take random things like that personally.

**Comment by YRUSpawnCamping** [comment]
It's wild that you believe there is a discussion to be had. As if the answer to "Should we be making fun of sexual assault" could be anything but a resounding NO. If you believe otherwise then you should look into yourself and ask "why do I believe this is up for debate?"

Asking to keep morality and social questions out of an area is what the people who are fine with the status quo do. You can't separate **anything** that people do from questions of morality and societal justice. There is no "morally neutral area" where humans are involved. If you think there is then you're not looking at it hard enough.

I'm not going to convince you. This is for anyone who might otherwise fall for your rhetoric tricks.

**Comment by q009** [comment]
Yes, this topic is not really debatable and there's no need to further discuss this. I'm locking the discussion.

**Comment by qreeves** [comment]
It's not a debate, and it's not up for discussion. I've stated my position and as someone who was actually subjected to this kind of assault as a child, I don't much care for people continually bumping this topic and reminding me of it all the time.

Up there on your white horse, you seem to be forgetting the etiquette necessary to approach a topic this sensitive with some tact. Congratulations on earning the first ever lifetime ban from Red Eclipse.
